### ISSUE TITLE
Fix script: build

### ISSUE THREAD

**Issue by ChadBailey** [ChadBailey/videospeed-refactoring#10]
```bash
> build
> cross-env NODE_ENV=development webpack --config ./webpack.config.js

[webpack-cli] Invalid configuration object. Webpack has been initialized using a configuration object that does not match the API schema.
 - configuration.entry should be one of these:
   function | object { <key>: [non-empty string, ...] (should not have fewer than 1 item, should not have duplicate items) | non-empty string | object { import, asyncChunks?, baseUri?, chunkLoading?, dependOn?, filename?, layer?, library?, publicPath?, runtime?, wasmLoading? } } | [non-empty string, ...] (should not have fewer than 1 item, should not have duplicate items) | non-empty string
   -> The entry point(s) of the compilation.
   Details:
    * configuration.entry[0] should be a non-empty string.
      -> A module that is loaded upon startup. Only the last one is exported.
    * configuration.entry[1] should be a non-empty string.
      -> A module that is loaded upon startup. Only the last one is exported.
    * configuration.entry[2] should be a non-empty string.
      -> A module that is loaded upon startup. Only the last one is exported.
[12:13 AM] ~/code/videospeed-refactoring (master) $ 
```

**Comment by ChadBailey** [comment]
Chrome-only dev working
Prod build of chrome-only not working:

```bash
[06:24 PM] ~/code/videospeed-refactoring (master) $ npx cross-env NODE_ENV=production webpack --config ./webpack/chrome.js
Debugger listening on ws://127.0.0.1:29129/1f137165-e3ca-45c4-a2f3-5b4d757e0b51
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Debugger listening on ws://127.0.0.1:29134/794031b0-d3de-4731-9b52-483a8b42dcd8
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
Debugger listening on ws://127.0.0.1:29137/0da4123f-e9b6-4816-9cfe-650c1e86157a
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
[webpack-cli] Failed to load 'C:\Users\chadb\code\videospeed-refactoring\webpack\chrome.js' config
[webpack-cli] TypeError: optimize.OccurrenceOrderPlugin is not a constructor
    at Object.<anonymous> (C:\Users\chadb\code\videospeed-refactoring\webpack\base.js:18:5)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
    at Module.load (node:internal/modules/cjs/loader:997:32)
    at Module._load (node:internal/modules/cjs/loader:838:12)
    at Module.require (node:internal/modules/cjs/loader:1021:19)
    at require (node:internal/modules/cjs/helpers:103:18)
    at Object.<anonymous> (C:\Users\chadb\code\videospeed-refactoring\webpack\chrome.js:3:5)
    at Module._compile (node:internal/modules/cjs/loader:1119:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1173:10)
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
Waiting for the debugger to disconnect...
[06:24 PM] ~/code/videospeed-refactoring (master) $ 
```

[ignore the poorly configured debugger]

**Comment by ChadBailey** [comment]
Fixed in https://github.com/ChadBailey/videospeed-refactoring/commit/f3d03493fcba107fec30b2918650e887f3909c51
