### ISSUE TITLE
Extension context invalidated

### ISSUE THREAD

**Issue by ChadBailey** [ChadBailey/videospeed-refactoring#12]
```
Uncaught Error: Extension context invalidated.
    at e (index.js:460:25)
    at HTMLDocument.<anonymous> (index.js:489:9)
```
https://github.com/ChadBailey/videospeed-refactoring/blob/939141b1af11b1d4f99423006ac8af859b086f54/src/content/index.js#L460-L465

**Comment by ChadBailey** [comment]
This has either been fixed, or I can no longer reproduce it. I'll re-open with steps if I can figure out how to reproduce (oops, should have included that originally)
