### ISSUE TITLE
DEP_WEBPACK_COMPILATION_ASSETS

### ISSUE THREAD

**Issue by ChadBailey** [ChadBailey/videospeed-refactoring#13]
```bash
$ cross-env NODE_ENV=development webpack --config ./webpack/chrome.js
[...]
rebuilding manifest.json
(node:17128) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by ChadBailey** [comment]
Documenting the full error with --trade-deprecation

```bash
[04:16 PM] ~/code/videospeed-refactoring (master) $ node --trace-deprecation node_modules/webpack/bin/webpack --config ./webpack/chrome.js
Debugger listening on ws://127.0.0.1:19731/72888386-ac1b-47dd-9350-1a5d4486485d
For help, see: https://nodejs.org/en/docs/inspector
Debugger attached.
WARNING: Development build only, not for use in prod

Rebuilding manifest.json
(node:9116) [DEP_WEBPACK_COMPILATION_ASSETS] DeprecationWarning: Compilation.assets will be frozen in future, all modifications are deprecated.
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
        Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
        Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
    at emit (C:\Users\chadb\code\videospeed-refactoring\node_modules\generate-json-from-js-webpack-plugin\index.js:52:41)
    at Hook.eval [as callAsync] (eval at create (C:\Users\chadb\code\videospeed-refactoring\node_modules\tapable\lib\HookCodeFactory.js:33:10), <anonymous>:7:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (C:\Users\chadb\code\videospeed-refactoring\node_modules\tapable\lib\Hook.js:18:14)
    at Compiler.emitAssets (C:\Users\chadb\code\videospeed-refactoring\node_modules\webpack\lib\Compiler.js:891:19)
    at C:\Users\chadb\code\videospeed-refactoring\node_modules\webpack\lib\Compiler.js:466:10
    at processTicksAndRejections (node:internal/process/task_queues:77:11)
    at runNextTicks (node:internal/process/task_queues:64:3)
    at process.processImmediate (node:internal/timers:442:9)
```
